// Shared child-appropriate vocabulary covering all content words used in the 10 demo books.
// BookReader checks book-specific vocab first, then falls back to this.
export const COMMON_VOCABULARY: Record<string, { definition: string; phonetic?: string }> = {
  // A
  across:         { definition: 'From one side to the other side of something.', phonetic: '/əˈkrɒs/' },
  after:          { definition: 'Following something in time or place.' },
  against:        { definition: 'Touching or pressing on the surface of something.' },
  algorithm:      { definition: 'A set of step-by-step instructions used to solve a problem.', phonetic: '/ˈæl.ɡə.rɪ.ðəm/' },
  alive:          { definition: 'Living and breathing; not dead.' },
  alphabet:       { definition: 'All the letters of a language arranged in order.', phonetic: '/ˈæl.fə.bɛt/' },
  apart:          { definition: 'Separated by a distance; not touching.' },
  asked:          { definition: 'Put a question to someone; requested something.' },
  arrived:        { definition: 'Reached a place after traveling.' },
  away:           { definition: 'At a distance from here; not present.' },

  // B
  bear:           { definition: 'A large, furry wild animal that hibernates in winter.', phonetic: '/bɛr/' },
  beautiful:      { definition: 'Very pleasing to look at; lovely.' },
  behind:         { definition: 'At the back of something.' },
  beneath:        { definition: 'Directly below; under something.' },
  bend:           { definition: 'To curve or change direction; not stay straight.' },
  billions:       { definition: 'A very large number — a thousand million (1,000,000,000).' },
  birch:          { definition: 'A type of tree with smooth, white or pale bark.', phonetic: '/bɜːrtʃ/' },
  bioluminescent: { definition: 'Able to make its own light, like some deep-sea fish and fireflies.', phonetic: '/ˌbaɪ.oʊ.luː.mɪˈnɛs.ənt/' },
  blue:           { definition: 'A color like the clear sky or the deep ocean.' },
  bright:         { definition: 'Giving off a lot of light; also very clever.' },
  broke:          { definition: 'Split apart into pieces; or stopped working.' },
  boulders:       { definition: 'Very large rocks, usually rounded and heavy.', phonetic: '/ˈboʊl.dərz/' },
  brown:          { definition: 'A dark color like chocolate or tree bark.' },
  brushed:        { definition: 'Lightly touched or stroked against something.' },

  // C
  caesar:         { definition: 'A famous ancient Roman ruler; also the name of a type of substitution code.', phonetic: '/ˈsiː.zər/' },
  came:           { definition: 'Moved toward; arrived at a place.' },
  carved:         { definition: 'Cut or shaped from a hard material like wood or stone.' },
  catch:          { definition: 'To grab something that is moving through the air.' },
  center:         { definition: 'The middle point or part of something.' },
  chunks:         { definition: 'Large, thick pieces of something solid.' },
  cipher:         { definition: 'A system of secret writing used to hide a message.', phonetic: '/ˈsaɪ.fər/' },
  clover:         { definition: 'A small plant with leaves that usually come in groups of three.', phonetic: '/ˈkloʊ.vər/' },
  clouds:         { definition: 'White or grey puffs in the sky made of tiny water droplets.' },
  cold:           { definition: 'Having a low temperature; not warm.' },
  collection:     { definition: 'A group of things that have been gathered together.' },
  colors:         { definition: 'The different hues we see, such as red, blue, green, and yellow.' },
  comes:          { definition: 'Moves toward; arrives at a place.' },
  contamination:  { definition: 'Making something dirty, poisonous, or unsafe by adding harmful substances.', phonetic: '/kənˌtæm.ɪˈneɪ.ʃən/' },
  count:          { definition: 'To say numbers in order; to find out how many things there are.' },
  could:          { definition: 'Was able to; had the ability to do something.' },
  cubs:           { definition: 'Young bears, lions, or other wild animals.', phonetic: '/kʌbz/' },
  curled:         { definition: 'Bent or coiled into a curved shape.' },

  // D
  dark:           { definition: 'With little or no light; the opposite of bright.' },
  data:           { definition: 'Facts and information collected to study or learn from.', phonetic: '/ˈdeɪ.tə/' },
  decrypt:        { definition: 'To decode a secret message so it can be read normally.', phonetic: '/diːˈkrɪpt/' },
  deeper:         { definition: 'Farther below the surface; more down than before.' },
  direction:      { definition: 'The way something is going or the path it takes.' },
  dipped:         { definition: 'Went down briefly into something, then came back up.' },
  dirt:           { definition: 'Loose soil or earth found on the ground.' },
  door:           { definition: 'A solid barrier that opens and closes an entrance.' },
  downstream:     { definition: 'In the direction the water flows in a river.', phonetic: '/ˈdaʊn.striːm/' },
  dragonfly:      { definition: 'An insect with four large, thin wings that lives near ponds and rivers.', phonetic: '/ˈdræɡ.ən.flaɪ/' },
  drops:          { definition: 'Tiny, round amounts of liquid; also falls downward.' },

  // E
  earth:          { definition: 'Our planet; also the dark soil in the ground.' },
  evidence:       { definition: 'Facts or objects that help prove something is true.', phonetic: '/ˈɛv.ɪ.dəns/' },
  every:          { definition: 'Each one of a group, without leaving any out.' },
  eyes:           { definition: 'The parts of the body used for seeing.' },
  explained:      { definition: 'Made something clear or easy to understand.' },

  // F
  face:           { definition: 'The front part of the head; also to look toward something.' },
  family:         { definition: 'A group of related people or animals living together.' },
  fish:           { definition: 'A cold-blooded animal with fins that lives and breathes in water.' },
  first:          { definition: 'Coming before all others; at the beginning.' },
  fixed:          { definition: 'Repaired so it works again; or stayed in one place.' },
  flip:           { definition: 'To turn over quickly, usually in the air.' },
  flippers:       { definition: 'Flat, paddle-shaped limbs that help animals swim, like on a turtle or seal.', phonetic: '/ˈflɪp.ərz/' },
  foaming:        { definition: 'Covered in bubbles; making a bubbly froth.' },
  found:          { definition: 'Discovered something; came across something by chance.' },
  frog:           { definition: 'A small, jumping animal that lives near water and breathes both in water and on land.' },

  // G
  giant:          { definition: 'Much larger than normal; extremely big.' },
  give:           { definition: 'To hand something to another person or animal.' },
  gleamed:        { definition: 'Shone with a soft, steady light.', phonetic: '/ɡliːmd/' },
  glided:         { definition: 'Moved smoothly and quietly through air or water.', phonetic: '/ˈɡlaɪ.dɪd/' },
  glowed:         { definition: 'Gave off a warm, steady light from inside.' },
  gold:           { definition: 'A shiny, precious yellow metal; also the bright yellow color of gold.' },
  grains:         { definition: 'Tiny particles of sand or salt; also seeds of wheat and other cereal plants.' },
  grade:          { definition: 'A level in school; also a mark that shows how well you did on schoolwork.' },
  green:          { definition: 'A color like grass, leaves, and many plants.' },
  grey:           { definition: 'A color between black and white, like storm clouds.' },
  grim:           { definition: 'Dark, stern, and unfriendly in appearance.' },
  ground:         { definition: 'The surface of the earth that you walk or stand on.' },

  // H
  harbor:         { definition: 'A sheltered area of water where ships and boats can stay safely.', phonetic: '/ˈhɑːr.bər/' },
  have:           { definition: 'To own or possess something; to experience something.' },
  heavy:          { definition: 'Weighing a lot; hard to lift or move.' },
  held:           { definition: 'Kept something in your hands or arms.' },
  high:           { definition: 'Far above the ground; at a great height.' },
  hole:           { definition: 'An opening or gap made in something.' },
  home:           { definition: 'The place where you live or belong.' },
  house:          { definition: 'A building where people live.' },
  hungry:         { definition: 'Feeling the need for food; wanting to eat.' },

  // I
  immediately:    { definition: 'At once; right away without any delay.', phonetic: '/ɪˈmiː.di.ɪt.li/' },
  inside:         { definition: 'In the inner part of something; not outside.' },
  into:           { definition: 'Going from outside to the inside of something.' },

  // J
  jump:           { definition: 'To push off the ground and move through the air.' },

  // K
  knew:           { definition: 'Had knowledge of something in the past.' },
  knelt:          { definition: 'Went down on one or both knees.', phonetic: '/nɛlt/' },

  // L
  large:          { definition: 'Big in size; greater than normal.' },
  later:          { definition: 'After some time has passed; not right now.' },
  letter:         { definition: 'A written symbol that makes a sound in a word; also a written message.' },
  life:           { definition: 'The ability to grow, move, and change; the time you are alive.' },
  light:          { definition: 'Energy that lets us see; also something that is not heavy.' },
  like:           { definition: 'Similar to something; also to enjoy or be fond of something.' },
  little:         { definition: 'Small in size or amount.' },
  lived:          { definition: 'Was alive; made a home somewhere.' },
  locker:         { definition: 'A small metal cabinet, usually at school, for storing personal things.' },
  long:           { definition: 'Having great length; taking a lot of time.' },
  loved:          { definition: 'Had strong, warm feelings of care and affection.' },

  // M
  made:           { definition: 'Created or built something.' },
  magnificent:    { definition: 'Extremely beautiful and impressive; splendid.', phonetic: '/mæɡˈnɪf.ɪ.sənt/' },
  make:           { definition: 'To create or build something.' },
  mama:           { definition: 'A mother (informal word used by young children).' },
  manor:          { definition: 'A large, grand house in the country, often with land around it.', phonetic: '/ˈmæn.ər/' },
  many:           { definition: 'A large number of things or people.' },
  massive:        { definition: 'Extremely large and heavy.', phonetic: '/ˈmæs.ɪv/' },
  message:        { definition: 'Information sent from one person to another.' },
  metal:          { definition: 'A hard, shiny material like iron, gold, or silver that can be shaped.' },
  million:        { definition: 'The number 1,000,000 — a thousand thousands.' },
  moor:           { definition: 'A wide, open area of land covered with rough grass and heather, usually with few trees.', phonetic: '/mʊər/' },
  more:           { definition: 'A greater amount or number of something.' },
  morning:        { definition: 'The early part of the day, from when the sun rises until noon.' },
  moving:         { definition: 'Going from one place to another; changing position.' },
  mystery:        { definition: 'Something strange or unknown that needs to be solved or explained.', phonetic: '/ˈmɪs.tər.i/' },

  // N
  nearest:        { definition: 'Closest in distance or space.' },
  nitrile:        { definition: 'A type of synthetic rubber used to make protective gloves.', phonetic: '/ˈnaɪ.traɪl/' },
  number:         { definition: 'A symbol or word used for counting and measuring.' },

  // O
  ocean:          { definition: 'The vast body of salt water that covers most of the Earth.', phonetic: '/ˈoʊ.ʃən/' },
  only:           { definition: 'And nothing or no one else; just one.' },
  orange:         { definition: 'A warm color between red and yellow; also a round citrus fruit.' },
  orbit:          { definition: 'The curved path an object follows as it travels around a planet or star.', phonetic: '/ˈɔːr.bɪt/' },
  other:          { definition: 'A different one; the remaining one.' },

  // P
  past:           { definition: 'On the far side of; gone beyond something; also time that has already happened.' },
  passes:         { definition: 'Goes through or by something; moves from one place to another.' },
  peeked:         { definition: 'Looked at something quickly and secretly.' },
  planet:         { definition: 'A large, round object in space that orbits a star. Earth is a planet.', phonetic: '/ˈplæn.ɪt/' },
  plasma:         { definition: 'A super-hot state of matter, like what makes up the sun and lightning.', phonetic: '/ˈplæz.mə/' },
  played:         { definition: 'Had fun doing games or activities.' },
  poisoning:      { definition: 'Making something harmful by adding a toxic or dangerous substance.' },
  pond:           { definition: 'A small, still body of water, smaller than a lake.', phonetic: '/pɒnd/' },
  porthole:       { definition: 'A small, round window in the side of a ship or submarine.', phonetic: '/ˈpɔːrt.hoʊl/' },
  pressed:        { definition: 'Pushed firmly against something.' },
  prove:          { definition: 'To show that something is true using facts or evidence.' },
  pulled:         { definition: 'Moved something toward you with force.' },

  // R
  rain:           { definition: 'Water that falls as drops from clouds in the sky.' },
  rainbow:        { definition: 'A curved band of colors in the sky, caused by sunlight passing through water droplets.', phonetic: '/ˈreɪn.boʊ/' },
  reached:        { definition: 'Stretched out to touch something; or arrived at a destination.' },
  ready:          { definition: 'Prepared and able to do something right now.' },
  recognized:     { definition: 'Knew who or what something was when you saw it.', phonetic: '/ˈrek.əɡ.naɪzd/' },
  refraction:     { definition: 'The bending of light when it passes from one material to another, like from air into water.', phonetic: '/rɪˈfræk.ʃən/' },
  remember:       { definition: 'To bring something back into your mind from the past.' },
  revealed:       { definition: 'Showed something that was previously hidden.', phonetic: '/rɪˈviːld/' },
  rings:          { definition: "Circles of material; Saturn's rings are made of rock, ice, and dust." },
  rising:         { definition: 'Going upward; moving to a higher position.' },
  river:          { definition: 'A large, natural flow of fresh water that runs across the land to the sea.' },
  rock:           { definition: 'A solid piece of natural stone or mineral material.' },
  rolled:         { definition: 'Moved by turning over and over; moved smoothly like a wheel.' },

  // S
  secrets:        { definition: 'Information or things kept hidden from others.' },
  seed:           { definition: 'A tiny object from a plant that grows into a new plant when planted.', phonetic: '/siːd/' },
  sense:          { definition: 'To notice or become aware of something; also one of the five senses (sight, hearing, smell, taste, touch).' },
  shifted:        { definition: 'Moved to a different position; changed slightly.' },
  showed:         { definition: 'Let someone see something; demonstrated or proved something.' },
  silent:         { definition: 'Making absolutely no sound; completely quiet.' },
  slept:          { definition: 'Was in a state of sleep; rested with eyes closed.' },
  slow:           { definition: 'Not moving quickly; taking more time than usual.' },
  small:          { definition: 'Little in size; not large.' },
  soil:           { definition: 'The top layer of the earth where plants grow; rich earth.', phonetic: '/sɔɪl/' },
  something:      { definition: 'A thing that is not known exactly or not named.' },
  spade:          { definition: 'A tool for digging in the ground, like a shovel with a flat blade.', phonetic: '/speɪd/' },
  sprout:         { definition: 'A tiny new plant just starting to grow from a seed.', phonetic: '/spraʊt/' },
  star:           { definition: 'A huge ball of burning gas in space. Our sun is a star.' },
  stars:          { definition: 'Huge balls of burning gas in space that look like tiny lights at night.' },
  steps:          { definition: 'Actions taken one after another to reach a goal; also the flat parts of stairs.' },
  stood:          { definition: 'Was in an upright position; remained in one place.' },
  strange:        { definition: 'Unusual or unfamiliar; not what you normally expect.' },
  stretched:      { definition: 'Reached out to its full length; extended over a large area.' },
  struck:         { definition: 'Hit something with force; also suddenly noticed or realized.' },
  submarine:      { definition: 'A vessel that can travel completely underwater.', phonetic: '/ˈsʌb.məˌriːn/' },
  sunflower:      { definition: 'A tall plant with large, bright yellow petals and a round dark center.', phonetic: '/ˈsʌn.flaʊ.ər/' },
  sunlight:       { definition: 'The natural light that comes from the sun.' },
  surface:        { definition: 'The outside or top layer of something.' },

  // T
  that:           { definition: 'Used to point to a specific thing; also joins two parts of a sentence.' },
  three:          { definition: 'The number 3; one more than two.' },
  through:        { definition: 'Going from one side to the other; from start to finish.' },
  tiny:           { definition: 'Very, very small; smaller than little.' },
  together:       { definition: 'With each other; as a group, not separately.' },
  triangle:       { definition: 'A flat shape with exactly three straight sides and three corners.', phonetic: '/ˈtraɪ.æŋ.ɡəl/' },
  tumbled:        { definition: 'Fell or rolled in an untidy, uncontrolled way.' },
  turtle:         { definition: 'A slow-moving reptile covered by a hard shell; some live in the sea, some on land.', phonetic: '/ˈtɜːr.tl/' },

  // V
  violet:         { definition: 'A blue-purple color; also a small flowering plant with purple or blue petals.', phonetic: '/ˈvaɪ.ə.lɪt/' },
  visible:        { definition: 'Able to be seen; not hidden.', phonetic: '/ˈvɪz.ɪ.bəl/' },

  // W
  waded:          { definition: 'Walked slowly through shallow water.', phonetic: '/ˈweɪ.dɪd/' },
  waiting:        { definition: 'Staying in one place until something happens or someone arrives.' },
  wall:           { definition: 'A solid upright structure that forms a side of a room or building.' },
  water:          { definition: 'A clear liquid that fills oceans, rivers, and lakes; living things need it to survive.' },
  waves:          { definition: 'Moving ridges that travel across the surface of water.' },
  when:           { definition: 'At the time that something happens.' },
  where:          { definition: 'In or at what place; the location of something.' },
  whole:          { definition: 'Complete; all of something; not just part of it.' },
  wide:           { definition: 'Having a large distance from one side to the other; broad.' },
  wings:          { definition: 'Parts of an animal used for flying; also sections of a large building.' },
  winking:        { definition: 'Closing one eye quickly as a playful or secret signal.', phonetic: '/ˈwɪŋ.kɪŋ/' },
  winter:         { definition: 'The coldest season of the year, coming after autumn.' },
  woke:           { definition: 'Stopped sleeping and became fully awake.' },

  // Y
  yellow:         { definition: 'A bright, warm color like the sun or a ripe lemon.' },
};
